minecraft_item_regexes = [
  [/^air$/i, 0]
  [/^stone$/i, 1]
  [/^grass$/i, 2]
  [/^dirt$/i, 3]
  [/^cobble(stone)?$/i, 4]
  [/plank(s)?$/i, 5]
  [/^sap/i, 6]
  [/^bedrock$/i, 7]
  [/^(still)?(.*)water$/i, 8]
  [/^(sta)?(.*)water$/i, 9]
  [/^lava$/i, 10]
  [/^(sta)?(.*)lava$/i, 11]
  [/^sand$/i, 12]
  [/^gravel$/i, 13]
  [/^gold(_)?ore$/i, 14]
  [/^iron(_)?ore$/i, 15]
  [/^coal(_)?ore$/i, 16]
  [/^(wood|log)$/i, 17]
  [/^lea(f|ve)(s)?$/i, 18]
  [/^sponge$/i, 19]
  [/^glass$/i, 20]
  [/^lapis(.*)ore$/i, 21]
  [/^lapis/i, 22]
  [/^dispenser$/i, 23]
  [/^sandstone$/i, 24]
  [/^note/i, 25]
# [/^bed(.*)block$/i, 26]
  [/^power(.*)(rail|track)$/i, 27]
  [/^detect(.*)(rail|track)$/i, 28]
  [/^stick(.*)piston$/i, 29]
  [/web$/i, 30]
  [/^(tallgrass|shrub|fern)$/i, 31]
  [/^deadshrub$/i, 32]
  [/^piston$/i, 33]
# [/^piston(.*)head$/i, 34]
  [/^wool$/i, 34]

  [/^ink/i, 351]
]